frontend/controllers/GameController.php
<?php

namespace frontend\controllers;

class GameController extends \yii\web\Controller
{
    public function actionIndex()
    {
        return $this->render('index');
    }

}

frontend/views/layouts/admin.php
<?php
/**
 * @var $this \yii\web\View
 * @var $content string
 */
use yii\helpers\Url;
use yii\helpers\Html;
use common\helpers\HtmlSettingsHelper;


$lang = HtmlSettingsHelper::getLang();
$charset = HtmlSettingsHelper::getCharset();
$pingback = HtmlSettingsHelper::getPingBackUrl();
$favicon = HtmlSettingsHelper::getFavicon();
\frontend\assets\AppAsset::register($this);


$isGuest = Yii::$app->user->isGuest;

$newWithdrawalRequests = \common\models\transactions\FinanceWithdrawalMoneyTransaction::query()->andWhere(['status' => \common\models\Transaction::STATUS_IN_PROCESS])->count();

?>
<?php $this->beginPage() ?>

    <!DOCTYPE html>
    <!--[if lt IE 7]>
    <html class="lt-ie7" lang="<?=$lang?>"> <![endif]-->
    <!--[if IE 7]>
    <html class="lt-ie8" lang="<?=$lang?>"> <![endif]-->
    <!--[if IE 8]>
    <html class="lt-ie9" lang="<?=$lang?>"> <![endif]-->
    <!--[if gt IE 8]><!-->
    <html lang="<?= $lang ?>">


    <!-- Added by HTTrack -->
    <meta http-equiv="content-type" content="text/html;charset=UTF-8"/>
    <!-- /Added by HTTrack -->
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta charset="<?= $charset ?>">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="profile" href="http://gmpg.org/xfn/11">
        <link rel="pingback" href="<?= $pingback ?>">


        <link rel="shortcut icon" href="<?= $favicon ?>"/>

        <?= Html::csrfMetaTags() ?>
        <title><?= Html::encode($this->title) ?></title>
        <?php $this->head() ?>

    </head>


    <body class="<?= HtmlSettingsHelper::getPageClass() ?>">

    <?php $this->beginBody() ?>

    <div class="perfectScroll">
        <!-- Preloader -->
        <div class="page-preloader preloader-wrapp">
            <img src="/img/logo.png" alt="">

            <div class="preloader"></div>
        </div>
        <!-- /Preloader -->

        <!-- Navbar -->
        <nav class="navbar-youplay navbar navbar-default navbar-fixed-top ">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="off-canvas" data-target="#navbar"
                            aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?= Yii::$app->homeUrl ?>">
                        <img src="/img/logo.png" alt="">
                    </a>
                </div>


                <div id="navbar" class="navbar-collapse collapse">

                    <?= $this->render('parts/_main_menu') ?>
                </div>
            </div>
        </nav>
        <!-- /Navbar -->


        <!-- Main Content -->
        <section class="content-wrap">

            <!-- Banner -->
            <div class="youplay-banner youplay-banner-parallax banner-top youplay-banner-parallax small">
                <div class="image" style="background-image: url('/img/game-diablo-iii-1400x656.jpg')">
                </div>


                <div class="info">
                    <div class="container">
                        <div class="square purpure admin-column">
                            <h4>Страницы</h4>

                            <div class="line red  mb-10"></div>
                            <div class="inline-block"><a href="<?= Url::to(['site/index']) ?>">Лендинг</a></div>
                            <div class="inline-block"><a href="<?= \common\models\User::getCurrentUser()->getUrl() ?>">Кабинет</a>
                            </div>
                            <div class="inline-block"><a href="<?= Url::to(['game/index']) ?>">Игры</a></div>

                        </div>

                        <div class="square purpure admin-column">
                            <h4>Управление</h4>

                            <div class="line red  mb-10"></div>
                            <div class="inline-block"><a href="<?= Url::to(['admin/history']) ?>">История транзакций</a>
                            </div>
                            <div class="inline-block"><a href="<?= Url::to(['admin/withdrawal']) ?>">Запросы на вывод
                                    <?php if ($newWithdrawalRequests): ?>
                                        <span class="badge pull-right bg-default"><?= $newWithdrawalRequests ?></span>
                                    <?php endif; ?>
                                </a>
                            </div>
                            <div class="inline-block"><a href="<?= Url::to(['admin/index']) ?>">Статистика</a></div>
                        </div>

                        <div class="square purpure admin-column two-columns">
                            <h4>Редактирование</h4>

                            <div class="line red mb-10"></div>
                            <?php foreach (\frontend\controllers\AdminController::slugLabels() as $slug => $label): ?>
                                <div class="inline-block"><a
                                        href="<?= Url::to(['admin/edit', 'slug' => $slug]) ?>"><?= $label ?></a></div>
                            <?php endforeach; ?>
                        </div>

                    </div>
                </div>

            </div>
            <!-- /Banner -->
            <section class="pt-20">
                <div class=" pb-40">
                    <div class="row">
                        <div class="col-md-6 col-md-offset-3">
                            <?=
                            \frontend\helpers\NotifyMessages::widget();
                            ?>
                        </div>
                    </div>

                    <h5 class="text-center">Серверное время</h5>
                    <h3 class="text-center mb-40" data-toggle="time" data-timestamp="<?= time()?>"><span class="fa fa-calendar"></span> <span class="date-cnt"><?= date('d.m.Y')?></span> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="fa fa-clock-o"></span> <span class="time-cnt"><?= date('H.i.s')?></span> </h3>

                    <?= $content ?>
                </div>

                <!-- Footer -->
                <footer class="mt-60">


                    <?= $this->render('parts/_copyright')?>

                </footer>
            </section>
            <!-- /Footer -->

        </section>
        <!-- /Main Content -->

        <!-- Search Block -->
        <div class="search-block">
            <a href="#!" class="search-toggle glyphicon glyphicon-remove"></a>

            <form action="http://html.nkdev.info/youplay/dark/search.html">
                <div class="youplay-input">
                    <input type="text" name="search" placeholder="Search...">
                </div>
            </form>
        </div>
        <!-- /Search Block -->


        <div>
            <a href="/game" class="left-fixed square green hover transparent-2">
                <img src="/img/joistik.png" alt="" height="20"/>
            </a>


        </div>
    </div>
    <?php $this->endBody() ?>


    </body>
    </html>

<?php $this->endPage() ?>

frontend/views/layouts/auth.php
<?php
/**
 * @var $this \yii\web\View
 * @var $content string
 */
use yii\helpers\Url;
use yii\helpers\Html;
use common\helpers\HtmlSettingsHelper;


$lang = HtmlSettingsHelper::getLang();
$charset = HtmlSettingsHelper::getCharset();
$pingback = HtmlSettingsHelper::getPingBackUrl();
$favicon = HtmlSettingsHelper::getFavicon();
\frontend\assets\AppAsset::register($this);


$isGuest = Yii::$app->user->isGuest;



?>
<?php $this->beginPage() ?>

    <!DOCTYPE html>
    <!--[if lt IE 7]>  <html class="lt-ie7" lang="<?=$lang?>"> <![endif]-->
    <!--[if IE 7]>     <html class="lt-ie8" lang="<?=$lang?>"> <![endif]-->
    <!--[if IE 8]>     <html class="lt-ie9" lang="<?=$lang?>"> <![endif]-->
    <!--[if gt IE 8]><!-->
    <html lang="<?=$lang?>">


    <!-- Added by HTTrack --><meta http-equiv="content-type" content="text/html;charset=UTF-8" /><!-- /Added by HTTrack -->
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta charset="<?= $charset?>">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="profile" href="http://gmpg.org/xfn/11">
        <link rel="pingback" href="<?= $pingback ?>">


        <link rel="shortcut icon" href="<?= $favicon?>" />

        <?= Html::csrfMetaTags() ?>
        <title><?= Html::encode($this->title) ?></title>
        <?php $this->head() ?>

    </head>


    <body class="<?= HtmlSettingsHelper::getPageClass()?>">

    <?php $this->beginBody() ?>

    <div class="perfectScroll">

    <!-- Preloader -->
    <div class="page-preloader preloader-wrapp">
        <img src="/img/logo.png" alt="">
        <div class="preloader"></div>
    </div>
    <!-- /Preloader -->

    <!-- Navbar -->
    <nav class="navbar-youplay navbar navbar-default navbar-fixed-top ">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="off-canvas" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="<?= Yii::$app->homeUrl?>">
                    <img src="/img/logo.png" alt="">
                </a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <?= $this->render(!$isGuest ? 'parts/_main_menu' : 'parts/_landing_menu')?>
            </div>
        </div>
    </nav>
    <!-- /Navbar -->


    <!-- Main Content -->
    <section class="content-wrap youplay-login" style="min-height:100% !important;">

        <!-- Banner -->
        <div class="pb-100 youplay-banner banner-top youplay-banner-parallax small" style="height:100%; min-height: 100vh;">
            <div class="image" style="background-image: url('/img/game-diablo-iii-1400x656.jpg')">
            </div>

            <div style="margin-top:16px;">
                <?= $content ?>
            </div>


        </div>
        <!-- /Banner -->
        <section class="bg-pictures">


            <!-- Footer -->
            <footer style="margin-top:-78px;">


                <?= $this->render('parts/_copyright')?>

            </footer>
        </section>
        <!-- /Footer -->

    </section>
    <!-- /Main Content -->

    <!-- Search Block -->
    <div class="search-block">
        <a href="#!" class="search-toggle glyphicon glyphicon-remove"></a>
        <form action="http://html.nkdev.info/youplay/dark/search.html">
            <div class="youplay-input">
                <input type="text" name="search" placeholder="Search...">
            </div>
        </form>
    </div>
    <!-- /Search Block -->





    <?php $this->endBody() ?>
</div>

    </body>
    </html>

<?php $this->endPage() ?>

frontend/views/layouts/clearLayout.php
<?php
/**
 * @var $this \yii\web\View
 * @var $content string
 */
?>
<?= $content?>

frontend/views/layouts/game.php
<?php
/**
 * @var $this \yii\web\View
 * @var $content string
 */
use yii\helpers\Url;
use yii\helpers\Html;
use common\helpers\HtmlSettingsHelper;


$lang = HtmlSettingsHelper::getLang();
$charset = HtmlSettingsHelper::getCharset();
$pingback = HtmlSettingsHelper::getPingBackUrl();
$favicon = HtmlSettingsHelper::getFavicon();
\frontend\assets\AppAsset::register($this);


$isGuest = Yii::$app->user->isGuest;

$isGuest = false;


?>
<?php $this->beginPage() ?>

    <!DOCTYPE html>
    <!--[if lt IE 7]>
    <html class="lt-ie7" lang="<?=$lang?>"> <![endif]-->
    <!--[if IE 7]>
    <html class="lt-ie8" lang="<?=$lang?>"> <![endif]-->
    <!--[if IE 8]>
    <html class="lt-ie9" lang="<?=$lang?>"> <![endif]-->
    <!--[if gt IE 8]><!-->
    <html lang="<?= $lang ?>">


    <!-- Added by HTTrack -->
    <meta http-equiv="content-type" content="text/html;charset=UTF-8"/>
    <!-- /Added by HTTrack -->
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta charset="<?= $charset ?>">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="profile" href="http://gmpg.org/xfn/11">
        <link rel="pingback" href="<?= $pingback ?>">


        <link rel="shortcut icon" href="<?= $favicon ?>"/>

        <?= Html::csrfMetaTags() ?>
        <title><?= Html::encode($this->title) ?></title>
        <?php $this->head() ?>

    </head>


    <body class="<?= HtmlSettingsHelper::getPageClass() ?>">

    <?php $this->beginBody() ?>

    <div class="perfectScroll">
        <!-- Preloader -->
        <div class="page-preloader preloader-wrapp">
            <img src="/img/logo.png" alt="">

            <div class="preloader"></div>
        </div>
        <!-- /Preloader -->

        <!-- Navbar -->
        <nav class="navbar-youplay navbar navbar-default navbar-fixed-top ">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="off-canvas" data-target="#navbar"
                            aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?= Yii::$app->homeUrl ?>">
                        <img src="img/logo.png" alt="">
                    </a>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    <?= $this->render(!$isGuest ? 'parts/_main_menu' : 'parts/_landing_menu') ?>
                </div>
            </div>
        </nav>
        <!-- /Navbar -->


        <!-- Main Content -->
        <section class="content-wrap">

            <!-- Banner -->
            <div class="youplay-banner banner-top youplay-banner-parallax small">
                <div class="image" style="background-image: url('/img/game-diablo-iii-1400x656.jpg')">
                </div>


                <?php if (!$isGuest): echo $this->render('parts/_game_menu'); ?>

                    <div class="info">
                        <div>
                            <div class="container youplay-user">
                                <a class="angled-img">
                                    <div class="img">
                                        <img src="<?= \common\models\User::getCurrentUser()->pic ?>" alt="">
                                    </div>
                                </a>
                                <!--
                                    -->
                                <div class="user-data  mb-20" style="vertical-align: top;">
                                    <h2 class="text-center"><?= $user->username ?></h2>
                                    <!--                            <div class="location"><i class="fa fa-map-marker"></i> Los Angeles</div>-->
                                    <div class="">
                                        <div>
                                            <!--                                    <div class="num">69</div>-->
                                            <!--                                    <div class="title">Posts</div>-->
                                        </div>
                                        <div class="text-center">
                                            <h1 class="mt-15 mb-0">$500</h1>

                                            <div class="help-block">баланс</div>
                                        </div>
                                        <div>
                                            <!--                                    <div class="num">689</div>-->
                                            <!--                                    <div class="title">Followers</div>-->
                                        </div>
                                    </div>
                                </div>

                                <a href="/profile" class="user-data ml-60 no-style hover" style="vertical-align: top;">
                                    <h2 class="fa fa-bar-chart" style="font-size: 80px"></h2>
                                    <!--                            <div class="location"><i class="fa fa-map-marker"></i> Los Angeles</div>-->
                                    <div class="">
                                        <div>
                                            <!--                                    <div class="num">69</div>-->
                                            <!--                                    <div class="title">Posts</div>-->
                                        </div>
                                        <div class="text-center">
                                            <p>Главная</p>
                                        </div>
                                        <div>
                                            <!--                                    <div class="num">689</div>-->
                                            <!--                                    <div class="title">Followers</div>-->
                                        </div>
                                    </div>
                                </a>
                            </div>


                            <!--                    <div class="container mt-20">-->
                            <!--                        <a href="#!" class="btn btn-sm btn-default ml-0">Add Friend</a>-->
                            <!--                        <a href="#!" class="btn btn-sm btn-default">Private Message</a>-->
                            <!--                    </div>-->
                        </div>
                    </div>
                <?php else: ?>
                    <h1><?= $this->title ?></h1>

                <?php endif; ?>

            </div>
            <!-- /Banner -->
            <section class="bg-pictures <?= $isGuest ? "pt-70" : "pt-20" ?>">
                <div class=" pb-40">
                    <?= $content ?>
                </div>

                <!-- Footer -->
                <footer class="mt-60">


                    <div class="mb-40">
                        <?= $this->render('parts/_footer_social') ?>
                    </div>

                    <!-- Partners -->
                    <section class="youplay-banner youplay-banner-parallax small text-center">

                        <div class="image" style="background-image: url('/img/landing-block-5-bg.jpg');">
                        </div>


                        <img height="70" src="/img/logo.png" alt="pay system"/>

                    </section>



                    <?= $this->render('parts/_copyright')?>


                </footer>
            </section>
            <!-- /Footer -->

        </section>
        <!-- /Main Content -->

        <!-- Search Block -->
        <div class="search-block">
            <a href="#!" class="search-toggle glyphicon glyphicon-remove"></a>

            <form action="http://html.nkdev.info/youplay/dark/search.html">
                <div class="youplay-input">
                    <input type="text" name="search" placeholder="Search...">
                </div>
            </form>
        </div>
        <!-- /Search Block -->


        <a href="/profile" class="left-fixed no-style square green hover transparent-2">
            <span class="fa fa-bar-chart"></span>
        </a>

    </div>
    <?php $this->endBody() ?>


    </body>
    </html>

<?php $this->endPage() ?>

frontend/views/layouts/info.php
<?php
/**
 * @var $this \yii\web\View
 * @var $content string
 */
use yii\helpers\Url;
use yii\helpers\Html;
use common\helpers\HtmlSettingsHelper;


$lang = HtmlSettingsHelper::getLang();
$charset = HtmlSettingsHelper::getCharset();
$pingback = HtmlSettingsHelper::getPingBackUrl();
$favicon = HtmlSettingsHelper::getFavicon();
\frontend\assets\AppAsset::register($this);


$isGuest = Yii::$app->user->isGuest;


?>
<?php $this->beginPage() ?>

    <!DOCTYPE html>
    <!--[if lt IE 7]>
    <html class="lt-ie7" lang="<?=$lang?>"> <![endif]-->
    <!--[if IE 7]>
    <html class="lt-ie8" lang="<?=$lang?>"> <![endif]-->
    <!--[if IE 8]>
    <html class="lt-ie9" lang="<?=$lang?>"> <![endif]-->
    <!--[if gt IE 8]><!-->
    <html lang="<?= $lang ?>">


    <!-- Added by HTTrack -->
    <meta http-equiv="content-type" content="text/html;charset=UTF-8"/>
    <!-- /Added by HTTrack -->
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta charset="<?= $charset ?>">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="profile" href="http://gmpg.org/xfn/11">
        <link rel="pingback" href="<?= $pingback ?>">


        <link rel="shortcut icon" href="<?= $favicon ?>"/>

        <?= Html::csrfMetaTags() ?>
        <title><?= Html::encode($this->title) ?></title>
        <?php $this->head() ?>

    </head>


    <body class="<?= HtmlSettingsHelper::getPageClass() ?>">

    <?php $this->beginBody() ?>

    <div class="perfectScroll">
        <!-- Preloader -->
        <div class="page-preloader preloader-wrapp">
            <img src="/img/logo.png" alt="">

            <div class="preloader"></div>
        </div>
        <!-- /Preloader -->

        <!-- Navbar -->
        <nav class="navbar-youplay navbar navbar-default navbar-fixed-top ">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="off-canvas" data-target="#navbar"
                            aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?= Yii::$app->homeUrl ?>">
                        <img src="img/logo.png" alt="">
                    </a>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    <?= $this->render('parts/_landing_menu') ?>
                </div>
            </div>
        </nav>
        <!-- /Navbar -->


        <!-- Main Content -->
        <section class="content-wrap">


            <!-- Banner -->
            <div class="youplay-banner banner-top youplay-banner-parallax small">
                <div class="image" style="background-image: url('/img/game-diablo-iii-1400x656.jpg')">
                </div>

                <h1><?= $this->title ?></h1>


            </div>
            <!-- /Banner -->
            <section class="bg-pictures <?= "pt-20" ?>">
                <div class=" pb-40">
                    <?= $content ?>
                </div>

                <!-- Footer -->
                <footer class="mt-60">

                    <?php if ($isGuest): ?>
                        <div class="square purpure mb-40 full-width text-center">
                            <a class="parallelepiped no-style text-center light-blue dark-shadow hover p-20 ml-10"
                               style="width:125px" href="<?= Url::to(['auth/login']) ?>">Вход</a>

                            <a class="parallelepiped no-style text-center ping dark-shadow hover p-20 ml-30"
                               style="width:125px" href="<?= Url::to(['auth/signup']) ?>">Регистрация</a>
                        </div>
                    <?php endif; ?>



                    <div class="mb-40">
                        <?= $this->render('parts/_footer_social') ?>
                    </div>

                    <!-- Partners -->
                    <section class="youplay-banner youplay-banner-parallax small text-center">

                        <div class="image" style="background-image: url('/img/landing-block-5-bg.jpg');">
                        </div>


                        <img height="70" src="/img/logo.png" alt="pay system"/>

                    </section>


                    <?= $this->render('parts/_copyright')?>


                </footer>
            </section>
            <!-- /Footer -->

        </section>
        <!-- /Main Content -->

        <!-- Search Block -->
        <div class="search-block">
            <a href="#!" class="search-toggle glyphicon glyphicon-remove"></a>

            <form action="http://html.nkdev.info/youplay/dark/search.html">
                <div class="youplay-input">
                    <input type="text" name="search" placeholder="Search...">
                </div>
            </form>
        </div>
        <!-- /Search Block -->





        <?php $this->endBody() ?>

        </div>
    </body>
    </html>

<?php $this->endPage() ?>

frontend/views/layouts/landing.php
<?php
/**
 * @var $this \yii\web\View
 * @var $content string
 */
use yii\helpers\Url;
use yii\helpers\Html;
use common\helpers\HtmlSettingsHelper;


$lang = HtmlSettingsHelper::getLang();
$charset = HtmlSettingsHelper::getCharset();
$pingback = HtmlSettingsHelper::getPingBackUrl();
$favicon = HtmlSettingsHelper::getFavicon();
\frontend\assets\LandingAsset::register($this);

?>
<?php $this->beginPage() ?>

    <!DOCTYPE html>
    <!--[if lt IE 7]>
    <html class="lt-ie7" lang="<?=$lang?>"> <![endif]-->
    <!--[if IE 7]>
    <html class="lt-ie8" lang="<?=$lang?>"> <![endif]-->
    <!--[if IE 8]>
    <html class="lt-ie9" lang="<?=$lang?>"> <![endif]-->
    <!--[if gt IE 8]><!-->
    <html lang="<?= $lang ?>">


    <!-- Added by HTTrack -->
    <meta http-equiv="content-type" content="text/html;charset=UTF-8"/>
    <!-- /Added by HTTrack -->
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta charset="<?= $charset ?>">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="profile" href="http://gmpg.org/xfn/11">
        <link rel="pingback" href="<?= $pingback ?>">


        <link rel="shortcut icon" href="<?= $favicon ?>"/>

        <?= Html::csrfMetaTags() ?>
        <title><?= Html::encode($this->title) ?></title>
        <?php $this->head() ?>

    </head>


    <body class="<?= HtmlSettingsHelper::getPageClass() ?>">

    <?php $this->beginBody() ?>

    <div class="perfectScroll">

        <!-- Preloader -->
        <div class="page-preloader preloader-wrapp">
            <img src="/img/logo.png" alt="">

            <div class="preloader"></div>
        </div>
        <!-- /Preloader -->

        <!-- Navbar -->
        <nav class="navbar-youplay navbar navbar-default navbar-fixed-top ">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="off-canvas" data-target="#navbar"
                            aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?= Yii::$app->homeUrl ?>">
                        <img src="img/logo.png" alt="">
                    </a>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    <?= $this->render('parts/_landing_menu') ?>
                </div>
            </div>
        </nav>
        <!-- /Navbar -->


        <!-- Main Content -->
        <section class="content-wrap">

            <?= $content ?>

            <!-- Footer -->
            <footer class="">


                <?= $this->render('parts/_footer_social') ?>

                <div class="footer-menu text-center">
                    <a class="footer-link" href="#">Главная</a>
                    <a class="footer-link" href="#">О нас</a>
                    <a class="footer-link" href="#">Маркетинг</a>
                    <a class="footer-link" href="#">Новости</a>
                    <a class="footer-link" href="#">FAQ</a>
                </div>

                <div class="line grey"></div>


                <?= $this->render('parts/_copyright')?>

            </footer>
            <!-- /Footer -->

        </section>
        <!-- /Main Content -->

        <!-- Search Block -->
        <div class="search-block">
            <a href="#!" class="search-toggle glyphicon glyphicon-remove"></a>

            <form action="http://html.nkdev.info/youplay/dark/search.html">
                <div class="youplay-input">
                    <input type="text" name="search" placeholder="Search...">
                </div>
            </form>
        </div>
        <!-- /Search Block -->


    </div>
    <?php $this->endBody() ?>


    </body>
    </html>

<?php $this->endPage() ?>