frontend/controllers/AuthController.php
<?php

namespace frontend\controllers;

use Codeception\Module\MessageHelper;
use common\helpers\EmailHelper;
use common\models\Auth;
use common\models\User;
use frontend\models\auth\AdminLoginForm;
use frontend\models\auth\LoginForm;
use frontend\models\auth\ResetPasswordConfirmForm;
use frontend\models\auth\ResetPasswordForm;
use frontend\models\auth\SignUpForm;
use yii\authclient\ClientInterface;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;
use yii\web\Response;

class AuthController extends \yii\web\Controller
{
    public $layout='auth';


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['sign-up', 'log-in', 'reset-password', 'reset-password-confirm', 'auth', 'o-auth-success'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'actions'=> ['admin-login'],
                        'allow'=>true,
                        'matchCallback' => function ($rule, $action) {
                            if (\Yii::$app->user->isGuest) return false;

                            /**
                             * @var $user User
                             */
                            $user = \Yii::$app->user->getIdentity();

                            return $user->isAdmin();
                        }
                    ]
                ],
                'denyCallback'=>function($rule, $action) {
                    if (!\Yii::$app->user->isGuest) {
                        /**
                         * @var $user User
                         */
                        $user = \Yii::$app->user->getIdentity();

                        return $this->redirect($user->getUrl());
                    } else {
                        return $this->redirect(Url::to(['site/index']));
                    }
                }
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
            'auth' => [
                'class' => 'yii\authclient\AuthAction',
                'successCallback' => [$this, 'oAuthSuccess'],
            ],
        ];
    }


    public function actionLogIn() {


        $model = new LoginForm();

        if ($model->load($_POST) && $model->validate()) {
            if ($model->login())
                return $this->refresh();
        }


        return $this->render('login', ['model'=>$model]);
    }

    public function actionSignUp() {

        $model = new SignUpForm();

        if ($model->load($_POST) && $model->validate()) {
            if ($model->signUp()) {
                return $this->refresh();
            }
        }


        return $this->render('signup', ['model'=>$model]);
    }


    public function actionAdminLogin($code=null) {
        $model = new AdminLoginForm();
        $user = User::getCurrentUser();


        $send = false;
        if ($model->load($_POST)) {
            if ($model->validate() && $model->reset()) {
                return $this->redirect(Url::to(['admin/index']));
            }
        } else {
            if ($code) {
                $model->code = $code;
            } else {
                $user->email_expired_at = 0;
                $user->save();
                if ($user->email_expired_at < time()) {

                    $send = true;
                    $model->sendLetter();
                }
            }
        }

        return $this->render('admin-login', ['model'=>$model, 'sendBlock'=>$send]);
    }

    public function actionResetPassword() {

        $model = new ResetPasswordForm();

        if ($model->load($_POST) && $model->validate()) {
            if ($model->reset()) {
                return $this->redirect(Url::to(['auth/reset-password-confirm']));
            }
        }


        return $this->render('reset-password', ['model'=>$model]);
    }

    public function actionResetPasswordConfirm() {
        $model = new ResetPasswordConfirmForm();

        if ($model->load($_POST)) {
            if ($model->validate() && $model->reset()) {
                return $this->redirect(Url::to(['auth/reset-password-confirm']));
            }
        } else {
            $model->code = \Yii::$app->request->get('code', null);
        }

        return $this->render('reset-password-confirm', ['model'=>$model]);
    }

    public function actionLogout() {
        \Yii::$app->user->logout(true);
        return $this->refresh();
    }


    /**
     * This function will be triggered when user is successfuly authenticated using some oAuth client.
     *
     * @param ClientInterface $client
     * @return boolean|Response
     */
    public function oAuthSuccess($client) {
        // get user data from client

        $userAttributes = $client->getUserAttributes();

        $source = $client->getName();
        $auth_params = $client->getAccessToken()->getParams();
        $email = ArrayHelper::getValue($auth_params,'email',null);
        if (!$email) {
            $email = $source == "google" ? $userAttributes['emails'][0]["value"] : $userAttributes["email"];
        }
        $user = User::findByEmail($email);

        if (!$user) {
            $username = preg_split("/[^\w]/", $email)[0];
            while (User::findByUsername($username)) {
                $username = $username.rand(0,9);
            }
            $user = User::createNewUser($username, $email, \Yii::$app->security->generateRandomString(8));
        }
        $user->login();



        $sourceId = $userAttributes["id"];
        $uid = $user->id;
        $auth = Auth::find()->where([
            "user_id"=>$uid,
            "source"=>$source
        ])->one();

        if (!$auth) {
            $auth = new Auth();
        }

        $auth->user_id = $uid;
        $auth->source = $source;
        $auth->source_id = $sourceId;
        $auth->save();
        return $this->refresh();
    }

}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use common\helpers\SystemHelper;
use common\models\Article;
use common\models\Tariff;
use common\models\TariffToUser;
use common\models\transactions\TariffProfitTransaction;
use common\models\User;
use common\models\UserLikeArticle;
use Yii;
use yii\data\Pagination;
use yii\db\ActiveQuery;
use yii\db\Query;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;
use yii\web\Controller;

/**
 * Site controller
 */
class SiteController extends Controller
{
    public $layout = "info";

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        $this->layout='landing';

        if ($uname = Yii::$app->request->get('from', null)) {
            SystemHelper::setRefer($uname);
            return $this->redirect(Url::to(['auth/sign-up']));
        }

        return $this->render('index');
    }


    public function actionInvest() {
        return $this->render('invest');
    }


    public function actionPrograms() {
        return $this->render('programs');
    }

    public function actionFinances() {
        return $this->render('finances');
    }

    public function actionFaq() {
        $this->layout='info';
        return $this->render('faq');
    }



    public function actionMarketing() {
        $this->layout='info';
        return $this->render('marketing');
    }

    public function actionSupport() {
        return $this->render('support');
    }

    public function actionAbout() {
        $this->layout='info';
        return $this->render('about');
    }


    public function actionLicense() {
        $this->layout='info';
        return $this->render('license');
    }


    private static function  getPopularNews($query = null, $limit = 3) {
        if (!$query) {
            $query = Article::find();
        }


        return $query
            ->orderBy('likes desc, views desc, id')
            ->limit($limit)
            ->all();
    }

    public function actionDebug() {
        $this->layout = 'debug';

        return $this->render('index');
    }


    public function actionNews($q="", $category="") {
        $this->layout='info';

        $newsSearcher = Article::find();
        if (strlen($q)) {
            $newsSearcher->where(['like', 'title', $q]);
        }

        if (strlen($category)) {
            $newsSearcher->andWhere(['category_id'=>$category]);
        }

        $newsSearcher->orderBy('updated_at desc');

        // get the total number of articles (but do not fetch the article data yet)
        $count = $newsSearcher->count();

        // create a pagination object with the total count
        $pagination = new Pagination(['totalCount' => $count]);

        // limit the query using the pagination and retrieve the articles
        $articles = $newsSearcher->offset($pagination->offset)
            ->limit($pagination->limit)
            ->all();

        return $this->render('news', [
            'query'=>$q,
            'category' => $category,
            'popular' => $this->getPopularNews($newsSearcher),
            'articles' => $articles,
            'pagination' => $pagination,
            'count'=>$count
        ]);
    }

    public function actionArticle($id) {
        $model = Article::findOne(['id'=>$id]);
        $model->views += 1;
        $model->save();
        return $this->render('article', [
            'model'=>$model,
            'popular' => $this->getPopularNews(),
            'query'=>''
        ]);
    }

    public function actionCronCheckTariff() {


        //active inday tariffs
        foreach (TariffToUser::search(null, TariffToUser::STATUS_ACTIVE. null) as $tar) {
            /**
             * @var $tariff Tariff
             */
            $tariff = $tar->tariff;

            if (time() - $tar->cron_profit_at >= $tariff->frequency*60*60) {
                $amount = $tar->cost * $tariff->percent;
                $transaction = new TariffProfitTransaction($tar->user_id, $amount, $tar->id);
                $transaction->executeTransaction();
                $tar->profit += $amount;
                $tar->cron_profit_at += $tariff->frequency*60*60;
            }
            if ($tar->expired_at <= time()) {
                $tar->status = TariffToUser::STATUS_CLOSED;
            }
            $tar->save();
        }

    }


    public function actionGame() {
        $this->layout='game';
        return $this->render('game');
    }

    public function actionBoxes() {
        $this->layout='game';
        return $this->render('game-boxes');
    }


    public function actionLottery() {
        $this->layout='game';
        return $this->render('game-lottery');
    }


    public function actionLike($id) {
        $article = Article::findOne(['id'=>$id]);
        if (Yii::$app->user->isGuest) {
            return json_encode([
                "content" => $this->renderPartial('parts/_like_block', [
                    "article" => $article
                ])
            ]);
        }
        $user = User::getCurrentUser();

        $isLike = UserLikeArticle::find()
            ->where([
                'article_id'=>$article->id,
                'user_id'=>$user->id
            ])
            ->one();

        if ($isLike) {
            $isLike->delete();

            $article->likes--;
        } else {
            $nw = new UserLikeArticle();
            $nw->user_id = $user->id;
            $nw->article_id = $article->id;
            $nw->save();

            $article->likes++;
        }

        $article->save();


        return json_encode([
            "content"=>$this->renderPartial('parts/_like_block', [
                "article"=>$article
            ])
        ]);
    }
}

frontend/views/layouts/parts/__profile_submenu.php
<?php
use frontend\helpers\HtmlThemeHelper;
?>

<li class="menu-item current-menu-ancestor dropdown dropdown-hover">
    <a class="dropdown-toggle" data-toggle="dropdown" href="<?= \common\helpers\HtmlSettingsHelper::getUserProfileUrl()?>" role="button" aria-expanded="false">

        <span class="glyphicon glyphicon-user"></span><?= \common\models\User::getCurrentUser()->username?>
        <span class="fa fa-caret-down"></span>
        <span class="label">В кабинет </span>
    </a>

    <div class="dropdown-menu">
        <ul role="menu">

            <?= HtmlThemeHelper::getLiForProfileSubMenu('profile-index', \common\models\User::getCurrentUser()->getUrl(), 'Профиль')?>
            <?= HtmlThemeHelper::getLiForProfileSubMenu('site-news', \yii\helpers\Url::to(['site/news']), 'Новости')?>
            <?= HtmlThemeHelper::getLiForProfileSubMenu('site-support', \yii\helpers\Url::to(['site/support']), 'Техподдержка')?>
            <li>
                <a>
                    <?php \yii\widgets\ActiveForm::begin(['action'=>\yii\helpers\Url::to(['auth/logout'])]);?>

                    <button class="no-style no-padding no-margin">Выход</button>
                    <?php \yii\widgets\ActiveForm::end(); ?>
                </a>
            </li>

        </ul>
    </div>
</li>

<!--<li class="menu-item current-menu-ancestor">-->
<!--    <a href="#">-->
<!--        <span class="fa fa-arrows-alt" data-fullscreen data-toggle-class="noevents" data-toggle-general-events="fullscreenchange MSFullscreenChange mozfullscreenchange webkitfullscreenchange" data-toggle-from="fa-arrows-alt" data-toggle-to="fa-compress" ></span>-->
<!--    </a>-->
<!--</li>-->

frontend/views/layouts/parts/_copyright.php
<!-- Copyright -->
<div class="copyright" xmlns="http://www.w3.org/1999/html">
    <div class="container">
        <strong>You Play</strong> &copy; <?= date('Y') ?>. Все права <a href="<?= \yii\helpers\Url::to(['site/license'])?>"> защищены </a>
    </div>
</div>
<!-- /Copyright -->

frontend/views/layouts/parts/_footer_social.php
<?php

use common\models\Option;
?>

<div class="footer-social text-center">
    <a class="btn" href="<?= Option::getOption('social_facebook')?>"><span class="fa fa-facebook"></span></a>
    <a class="btn" href="<?= Option::getOption('social_instagram')?>"><span class="fa fa-instagram"></span></a>
    <a class="btn" href="<?= Option::getOption('social_skype')?>"><span class="fa fa-skype"></span></a>
    <a class="btn" href="<?= Option::getOption('social_telegram')?>"><span class="fa fa-telegram"></span></a>
    <a class="btn" href="<?= Option::getOption('social_vk')?>"><span class="fa fa-vk"></span></a>
</div>

frontend/views/layouts/parts/_game_menu.php
<div class="youplay-user-navigation">
    <div class="container">
        <ul>
            <li class="active"><a href="/game">Профиль</a></li>
            <li><a href="/boxes">YP кейсы</a></li>
            <li><a href="/lottery">YP лотерея</a></li>
            <li><a href="/game-game">YP game</a></li>
            <li><a href="/game-clans">YP кланы</a></li>
            <li><a href="/game-tickets">YP tickets</a></li>
        </ul>
    </div>
</div>

frontend/views/layouts/parts/_landing_menu.php
<?php
use yii\helpers\Url;
use frontend\helpers\HtmlThemeHelper;

/**
 * @var $user \common\models\User|null
 */
$user = Yii::$app->user->getIdentity();

?>

<ul class="nav navbar-nav" role="menu">
    <?= HtmlThemeHelper::getLiForLandingMenu("site-index", Url::to(['site/index']), 'страница',  'Главная')?>
    <?= HtmlThemeHelper::getLiForLandingMenu("site-about", Url::to(['site/about']), 'узнать', 'О нас')?>
    <?= HtmlThemeHelper::getLiForLandingMenu("site-marketing", Url::to(['site/marketing']), 'проекта', 'Маркетинг')?>
    <?= HtmlThemeHelper::getLiForLandingMenu("site-news", Url::to(['site/news']), 'новое', 'Новости')?>
    <?= HtmlThemeHelper::getLiForLandingMenu("site-faq", Url::to(['site/faq']), 'ответы', 'FAQ')?>

    <?php if(Yii::$app->user->isGuest): ?>
        <?= HtmlThemeHelper::getLiForLandingMenu("auth-login", Url::to(['auth/log-in']), 'на сайте', 'Авторизация')?>
    <?php else: ?>
    <?php endif; ?>

</ul>
<?php if (!Yii::$app->user->isGuest): ?>
<ul role="menu" class="nav navbar-nav navbar-right">

    <?= $this->render('__profile_submenu')?>

<!--    <li>-->
<!--        <a class="search-toggle" href="search.html">-->
<!--            <i class="fa fa-search"></i>-->
<!--        </a>-->
<!--    </li>-->

</ul>
<?php endif ?>

frontend/views/layouts/parts/_main_menu.php
<?php

/**
 * @var $this \yii\web\View
 */
?>

<ul class="nav navbar-nav navbar-right">


    <?= $this->render('__profile_submenu.php')?>

</ul>

frontend/views/layouts/parts/_profile_menu.php
<?php

use frontend\helpers\HtmlThemeHelper;
use yii\helpers\Url;


/**
 * @var $user \common\models\User
 */
$user = Yii::$app->user->getIdentity();
?>
<div class="youplay-user-navigation">
    <div class="container">
        <ul>

            <?= HtmlThemeHelper::getLiForProfileMenu('profile-index', \common\models\User::getCurrentUser()->getUrl(), 'Профиль')?>
            <?= HtmlThemeHelper::getLiForProfileMenu('profile-invest', Url::to(['profile/invest']), 'Инвестировать')?>
            <?= HtmlThemeHelper::getLiForProfileMenu('profile-finances', Url::to(['profile/finances']), 'Финансы')?>
            <?= HtmlThemeHelper::getLiForProfileMenu('profile-programs', Url::to(['profile/programs']), 'Реф. программа')?>
            <?= HtmlThemeHelper::getLiForProfileMenu('profile-history', Url::to(['profile/history']), 'История')?>
            <?= HtmlThemeHelper::getLiForProfileMenu('profile-settings', Url::to(['profile/settings']), 'Настройки')?>

        </ul>
    </div>
</div>

frontend/views/layouts/parts/_top_bar.php
<div class="top-bar">

</div>

frontend/views/layouts/parts/admin_link.php
<?php

if ($user = \common\models\User::getCurrentUser()):
    if ($user->isAdmin()):


        ?>

        <a href="/game" class="left-fixed square green hover transparent-2">
            <img src="/img/joistik.png" alt="" height="20"/>
        </a>


        <a href="<?= \yii\helpers\Url::to(['admin/index']) ?>"
           class="no-style left-fixed square red hover transparent-2 text-center"
           style="transform: rotateZ(-90deg); right:-7px;">
            <div class="no-style text-center fa fa-adn"></div>
            <div class="small">админка</div>
        </a>

    <?php
    endif;
endif;
?>